### ISSUE TITLE
Supports html

### ISSUE THREAD

**Issue by skjnldsv** [Cobertos/vue-input-contenteditable#6]
Hi!
Thanks a lot for your component!

It would be very nice if this would support html. That way we could have rendering like those:
![Capture d’écran_2020-10-06_15-21-27](https://user-images.githubusercontent.com/14975046/95206993-a743a480-07e7-11eb-90f2-adf23a24912a.png)

**Comment by Cobertos** [comment]
As of now, Vue has a ton of trouble with external things modifying it's HTML (in `contenteditable`'s case, the browser). I'm not sure if Vue 3 is any better, but the HTML update / diffing algorithm in Vue 2 tries to only do the minimal amount of work to update the DOM. `contenteditable` causes a lot of issues with this.

I have another component I made for https://tldh.ax that I might eventually release. It's a more general version of this one that can support stuff like HTML and takes a `<slot></slot>` instead of a `v-model`

For now, the narrow scope of this component makes it unsuitable for `contenteditable` with random HTML so I would consider it unsupported.

**Comment by skjnldsv** [comment]
We ended up implementing our own :)
Our use-case was too specific! :sweat_smile: 

Thanks anyway! Have a great day!
